"""Conformance fixtures, and the guard that makes the second door unforgettable.

Everything here is against a real DuckLake catalog on disk. ``PLAN.md`` is
unambiguous about why: "in-memory DuckDB demonstrably hides DuckLake failures
(constraint 7), so a fast in-memory path may exist for unit tests but must never
be the sole gate". There is therefore no in-memory option in this directory.

The fixtures are deliberately factories rather than ready-made objects. A
conformance test usually needs to choose its own scenario -- chunked or not, NULL
keys or not, append or update -- and a factory keeps that choice in the test
where it is readable, while still routing every scenario through
:class:`~harness.Parity` so both front doors are exercised without the test
having to remember them.

The door-choice guard
--------------------

``PLAN.md`` asks that front-door parity live in the suite rather than in review.
:class:`~harness.Parity` delivers that for any scenario built on it -- but
:func:`make_world` hands out a *single-door* world, which three tests genuinely
need, and nothing stopped a fourth from appearing by accident. A parity
guarantee that each new test has to remember to ask for is a guarantee that
decays quietly.

So :func:`_door_choice_guard` makes the choice mandatory. Any test that drives
the pipeline must do one of three things, and the third is a visible act:

1. go through :class:`~harness.Parity` (the ``parity`` / ``make_parity``
   fixtures), which runs both doors in lockstep and compares them; or
2. parametrise over :data:`harness.DOORS`, which runs both doors separately; or
3. appear in :data:`SINGLE_DOOR_EXEMPTIONS` with a written reason.

Adding a scenario therefore makes you choose. Forgetting is not one of the
options: a test that drives a ``World`` without doing any of the three fails
with an explanation rather than passing while covering half the surface.
"""

from __future__ import annotations

import inspect
from pathlib import Path
from typing import Callable

import pytest

from harness import ADDITIVE, DOORS, Landing, Parity, Scenario, World

HERE = Path(__file__).resolve().parent

#: Tests that legitimately drive one front door, and why. Every entry is a
#: deliberate exemption from the parity guarantee, so every entry needs a reason
#: that survives being read by someone else six months from now.
#:
#: Keep this list short. If a test is here because both doors were inconvenient
#: rather than impossible, the right fix is to move it onto ``Parity``.
SINGLE_DOOR_EXEMPTIONS: dict[str, str] = {
    "test_an_idle_trigger_opens_no_transaction": (
        "needs a spy StateStore and a RecordingConnection injected into the "
        "Engine. The CLI door builds its own Engine and owns its connection -- "
        "which is the property test_cli_contract.py verifies -- so neither can "
        "be passed in. The claim (no BEGIN for an empty plan) is about the "
        "engine's batch lifecycle, which both doors share verbatim."
    ),
    "test_merge_on_clause_contains_no_scalar_subquery": (
        "needs a RecordingConnection to capture the MERGE text the engine "
        "actually executed. The statement is generated by TableSink from a "
        "Model, and both doors reach it through the same Model, so recording it "
        "once through either door covers both."
    ),
    "test_run_drains_and_the_mart_is_readable_afterwards": (
        "the CLI *is* the door under test here: this is the only test that "
        "spawns a real process, and it is already parametrised over both "
        "invocations PLAN.md requires (python -m duckstream and the console "
        "script). A Python-API variant would not exercise anything new."
    ),
    "test_run_once_commits_a_single_batch": (
        "`--once` is a CLI flag. The Python API expresses the same thing as "
        "Once(), which harness.World.run(once=True) already drives through both "
        "doors elsewhere; this test is about the flag reaching it."
    ),
}

#: Fixtures that mean "this test drives the pipeline through both doors".
_PARITY_FIXTURES = frozenset({"parity", "make_parity"})

#: Fixtures that mean "this test drives the pipeline through one door".
_SINGLE_DOOR_FIXTURES = frozenset({"make_world"})

#: Set by :func:`pytest_collection_modifyitems` when it was able to check the
#: exemption list against a complete, unfiltered collection of this directory.
#: ``None`` means the check did not run -- a partial run, a ``-k`` filter -- and
#: the staleness test skips rather than reporting a false positive.
STALE_EXEMPTIONS: list[str] | None = None


def _is_conformance(item: pytest.Item) -> bool:
    """Is ``item`` collected from this directory?

    Needed because a directory-scoped ``pytest_collection_modifyitems`` is
    handed the **whole** session's item list, not just this directory's. Marking
    without this filter silently labels every unit test as a conformance test.
    """
    try:
        return HERE in Path(str(item.fspath)).resolve().parents
    except (OSError, ValueError):  # pragma: no cover - defensive
        return False


def _drives_the_pipeline(item: pytest.Item) -> bool:
    """Does this test run a model against a catalog?

    Two ways in: a fixture that hands out a world, or constructing
    :class:`~harness.World` in the test body -- which the CLI tests do, to read
    back a catalog a subprocess wrote.
    """
    names = set(getattr(item, "fixturenames", ()))
    if names & (_PARITY_FIXTURES | _SINGLE_DOOR_FIXTURES):
        return True
    return "World(" in _source_of(item)


def _source_of(item: pytest.Item) -> str:
    function = getattr(item, "function", None)
    if function is None:
        return ""
    try:
        return inspect.getsource(function)
    except (OSError, TypeError):  # pragma: no cover - defensive
        return ""


def _covers_both_doors(item: pytest.Item) -> str | None:
    """How this test covers both doors, or ``None`` if it does not.

    Both parametrisation styles put the door string into ``callspec.params``:
    ``@pytest.mark.parametrize("door", DOORS)`` and a fixture declared
    ``params=DOORS``. Checking the values rather than the parameter *name* means
    a test does not have to spell the parameter ``door`` to be recognised.
    """
    if set(getattr(item, "fixturenames", ())) & _PARITY_FIXTURES:
        return "Parity"
    callspec = getattr(item, "callspec", None)
    if callspec is not None and any(
        # Values are arbitrary objects and need not be hashable -- the CLI tests
        # parametrise over lists -- so compare rather than intersect.
        isinstance(value, str) and value in DOORS
        for value in callspec.params.values()
    ):
        return "parametrised over DOORS"
    return None


def pytest_collection_modifyitems(config: pytest.Config, items) -> None:
    """Mark this directory's tests, and audit the exemption list once.

    The staleness audit needs the complete, unfiltered collection of this
    directory to be meaningful -- under ``-k`` or a single-file run every
    exemption looks unused. When that is not the case it records ``None`` and
    the audit test skips, which is honest rather than merely quiet.
    """
    global STALE_EXEMPTIONS

    mine = [item for item in items if _is_conformance(item)]
    for item in mine:
        item.add_marker(pytest.mark.conformance)

    modules = {Path(str(item.fspath)).name for item in mine}
    expected = {path.name for path in HERE.glob("test_*.py")}
    filtered = bool(getattr(config.option, "keyword", "")) or bool(
        getattr(config.option, "markexpr", "")
    )
    if filtered or modules != expected:
        STALE_EXEMPTIONS = None
        return

    needed = {
        item.originalname or item.name
        for item in mine
        if _drives_the_pipeline(item) and _covers_both_doors(item) is None
    }
    STALE_EXEMPTIONS = sorted(set(SINGLE_DOOR_EXEMPTIONS) - needed)


@pytest.fixture(autouse=True)
def _door_choice_guard(request: pytest.FixtureRequest):
    """Refuse a pipeline test that silently covers one front door.

    Autouse, so it cannot be opted out of by forgetting to request it -- which
    is the failure mode the whole guard exists to prevent.
    """
    item = request.node
    if not _drives_the_pipeline(item):
        yield
        return

    coverage = _covers_both_doors(item)
    name = item.originalname or item.name
    if coverage is None and name not in SINGLE_DOOR_EXEMPTIONS:
        pytest.fail(
            f"{name} drives a model against a catalog but covers only one front "
            f"door, and PLAN.md requires every conformance scenario to run "
            f"through both.\n"
            f"Pick one:\n"
            f"  - use the `parity` or `make_parity` fixture, which runs both "
            f"doors in lockstep and compares them (preferred);\n"
            f"  - parametrise over harness.DOORS, e.g. "
            f"@pytest.mark.parametrize('door', DOORS);\n"
            f"  - if this test genuinely cannot use both -- it needs a "
            f"RecordingConnection, a spy StateStore, or the CLI process itself "
            f"-- add it to SINGLE_DOOR_EXEMPTIONS in "
            f"tests/conformance/conftest.py with the reason.",
            pytrace=False,
        )
    yield


@pytest.fixture
def single_door_exemptions() -> dict[str, str]:
    """The exemption list, for the test that audits it."""
    return dict(SINGLE_DOOR_EXEMPTIONS)


@pytest.fixture
def stale_exemptions() -> list[str] | None:
    """Exemptions that no longer apply, or ``None`` if the run was filtered."""
    return None if STALE_EXEMPTIONS is None else list(STALE_EXEMPTIONS)


# --------------------------------------------------------------------------
# Worlds
# --------------------------------------------------------------------------


@pytest.fixture
def landing(tmp_path: Path) -> Landing:
    """An empty landing tree, shared by both front doors of a scenario.

    Shared rather than duplicated on purpose: if the two doors read different
    trees, a parity failure could be a fixture difference rather than a
    duckstream difference, and the whole check would be weaker for it.
    """
    return Landing(tmp_path / "landing")


@pytest.fixture
def make_parity(tmp_path: Path, landing: Landing) -> Callable[..., Parity]:
    """Build a :class:`~harness.Parity` for a scenario, over the shared tree."""

    made: list[Parity] = []

    def factory(scenario: Scenario = ADDITIVE, *, name: str | None = None) -> Parity:
        label = name or f"case{len(made)}"
        parity = Parity(tmp_path / label, landing, scenario)
        made.append(parity)
        return parity

    return factory


@pytest.fixture
def parity(make_parity: Callable[..., Parity]) -> Parity:
    """The phase-1 additive scenario, behind both front doors."""
    return make_parity()


@pytest.fixture
def make_world(tmp_path: Path, landing: Landing) -> Callable[..., World]:
    """A single-door world, for tests where the two doors cannot move together.

    Fault injection is the main case: a killed process leaves one catalog
    mid-flight, and asserting about it needs that catalog on its own. Those
    tests parametrise over :data:`harness.DOORS` instead, so both doors are
    still covered -- just not in lockstep.

    Using this fixture without either parametrising over ``DOORS`` or appearing
    in :data:`SINGLE_DOOR_EXEMPTIONS` is a test failure; see
    :func:`_door_choice_guard`.
    """

    made: list[World] = []

    def factory(door: str, scenario: Scenario = ADDITIVE) -> World:
        world = World(door, tmp_path / f"{door}{len(made)}", landing, scenario)
        made.append(world)
        return world

    return factory
